FROM php:7.2-fpm

LABEL maintainer="Pavel Gavrilenko <paulgavrilenko@gmail.com>"

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
    curl \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
  && rm -rf /var/lib/apt/lists/*
  
RUN docker-php-ext-install pdo_mysql

RUN docker-php-ext-configure gd \
  --with-freetype-dir=/usr/include/freetype2 \
  --with-jpeg-dir=/usr/include \
  && docker-php-ext-install gd
    
RUN apt-get update && apt-get install -y libmagickwand-dev --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*
  
RUN printf "\n" | pecl install imagick
RUN docker-php-ext-enable imagick

RUN pecl install xdebug && \
  docker-php-ext-enable xdebug

RUN rm -rf /var/www/html